version: '3.9'
services:
    postgres:
        image: postgres
        #restart: always
        environment: 
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=todo_db
        # logging:
        #   options:
        #     max-size: 10m
        #     max-file: "3"
        ports:
          - '5433:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          #- ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql 